CREATE TABLE IF NOT EXISTS `FileConversionJob` (
  `id` VARCHAR(191) NOT NULL,
  `platform` ENUM('ANDROID', 'IOS') NOT NULL,
  `sourceName` VARCHAR(191) NOT NULL,
  `sourcePath` TEXT NOT NULL,
  `sourceMime` VARCHAR(191) NOT NULL,
  `sourceSize` INT NOT NULL,
  `sourceExtension` VARCHAR(191) NOT NULL DEFAULT '.png',
  `sourceSha1` VARCHAR(191) NULL,
  `bundleName` VARCHAR(191) NULL,
  `bundlePath` TEXT NULL,
  `bundleMime` VARCHAR(191) NULL,
  `bundleSize` INT NULL,
  `bundleExtension` VARCHAR(191) NULL,
  `bundleSha1` VARCHAR(191) NULL,
  `bundleSigningSha1` VARCHAR(191) NULL,
  `storeUploadExtensions` TEXT NULL,
  `status` ENUM('SUCCESS', 'FAILED') NOT NULL DEFAULT 'SUCCESS',
  `errorMessage` TEXT NULL,
  `createdById` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FileConversionJob_platform_createdAt_idx` (`platform`, `createdAt`),
  INDEX `FileConversionJob_createdById_idx` (`createdById`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `FileConversionResult` (
  `id` VARCHAR(191) NOT NULL,
  `jobId` VARCHAR(191) NOT NULL,
  `fileName` VARCHAR(191) NOT NULL,
  `filePath` TEXT NOT NULL,
  `mimeType` VARCHAR(191) NOT NULL,
  `fileExtension` VARCHAR(191) NOT NULL DEFAULT '.png',
  `sha1` VARCHAR(191) NULL,
  `signingSha1` VARCHAR(191) NULL,
  `fileSize` INT NOT NULL,
  `width` INT NOT NULL,
  `height` INT NOT NULL,
  `target` ENUM('APP_ICON', 'STORE_LISTING', 'APP_BUNDLE') NOT NULL,
  `storeEligible` TINYINT(1) NOT NULL DEFAULT 1,
  `usageNote` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `FileConversionResult_jobId_idx` (`jobId`),
  INDEX `FileConversionResult_target_idx` (`target`),
  INDEX `FileConversionResult_fileExtension_idx` (`fileExtension`),
  CONSTRAINT `FileConversionResult_jobId_fkey`
    FOREIGN KEY (`jobId`) REFERENCES `FileConversionJob`(`id`)
    ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
